// Generated by CoffeeScript 1.10.0
(function() {
  var assert, async, utils;

  async = require('async');

  assert = require('assert');

  utils = require('../lib/utils.js');

  describe('Test RedCross Shelters', function() {
    return it('should have a response', function(done) {
      utils.getShelters(function(err, result) {
        if (!result) {
          assert.fail(err, 'result');
        } else {
          assert(true, !!result);
        }
        return done();
      });
    });
  });

}).call(this);
