// Generated by CoffeeScript 1.10.0
(function() {
  var action, app, bodyParser, endpoints, express, http, i, len, middleware, morgan, point, redCross, utils, ware;

  bodyParser = require('body-parser');

  express = require('express');

  morgan = require('morgan');

  http = require('http');

  redCross = require('./lib/redCross.js');

  utils = require('./lib/utils.js');

  endpoints = {
    '/redcross/shelters': function(req, res) {
      return redCross.allShelters(req, res);
    },
    '/redcross/shelters/:lat/:long': function(req, res) {
      return redCross.closestShelters(req, res);
    }
  };

  middleware = [morgan('dev'), bodyParser.json(), utils.allowCrossDomain, express["static"](__dirname + "/public")];

  app = express();

  app.set("port", process.env.VCAP_APP_PORT || process.env.PORT || 8080);

  app.set("host", process.env.VCAP_APP_HOST || 'localhost');

  for (i = 0, len = middleware.length; i < len; i++) {
    ware = middleware[i];
    app.use(ware);
  }

  for (point in endpoints) {
    action = endpoints[point];
    app.get(point, action);
  }

  process.on('uncaughtException', function() {
    return console.log(err);
  });

  http.createServer(app).listen(app.get("port"), app.get("host"), function() {
    return console.log("Express server listening at http://" + app.get("host") + ':' + app.get("port"));
  });

}).call(this);
